### ISSUE TITLE
Updated offsets

### ISSUE THREAD

**Issue by FinleyVickers** [WCharacter/RainbowSixDmaKvm#5]
I just dumped the offsets of the newest version. I don't know what goes where in your offsets file though, so I thought I would just leave them here for someone who knows what they are doing.

R6GameManager : 0xFFFF8009B0BF0000 (0x0)
GameRenderer : 0xFFFF8009B0BF0000 (0x0)
LocalPlayerManager : 0xFFFF8009B0BF0000 (0x0)
StatusManager : 0xFFFF8009B0BF0000 (0x0)
NetworkManager : 0x5CFD160 (0x7FF65510D160)
RoundManager : 0xFFFF8009B0BF0000 (0x0)
InterfaceManager : 0xFFFF8009B0BF0000 (0x0)

**Comment by WCharacter** [comment]
These are not the relative offsets. This is currently working offsets. 
```
GameManager      -> 0x5DEC028
ProfileManager   -> 0x5E1B488 
RoundManager     -> 0x708BE38 
GlowManager      -> 0x5DF1ED0 
VTMarker           -> 0x1CC2C08 
FovManager       -> 0x6CF7A90 
RunAndShoot 1     -> 0x369FD27
RunAndShoot 2     -> 0x2518581 
PingThroughWalls -> 0x22F5CD4 
UnlockAll        -> 0x3836D34 
Silent           -> 0x1C44CB0
Recoil           -> 0x1C44C4D
Outline Bytepatch -> 0x374941F
```
